import { Link, useParams } from 'react-router-dom'
import { useAuth } from '../../../common/hooks/useAuth'
import { getAnalysisRecord } from '../../../common/services/analysisService'
import { AiDisclaimerBanner } from '../../../common/components/AiDisclaimerBanner'
import { StatusBadge } from '../../../common/components/StatusBadge'
import { ArrowLeftIcon, DownloadIcon, LockIcon } from '../../../common/components/icons'
import { formatDate } from '../../../common/utils/format'
import { renderMarkdown } from '../../../common/utils/renderMarkdown'

function AnalysisReportPage() {
  const { id } = useParams<{ id: string }>()
  const { account } = useAuth()

  if (!account) return null
  const report = id ? getAnalysisRecord(account.id, id) : undefined

  if (!report) {
    return (
      <div className="mx-auto max-w-xl py-16 text-center">
        <p className="text-sm font-medium text-slate-700">Report not found</p>
        <p className="mt-1 text-sm text-slate-500">
          This report may have been generated on another device — history is stored locally per browser.
        </p>
        <Link to="/dashboard" className="mt-4 inline-flex items-center gap-1.5 text-sm font-medium text-orange-600 hover:text-orange-700">
          <ArrowLeftIcon className="h-4 w-4" />
          Back to dashboard
        </Link>
      </div>
    )
  }

  const canExportPdf = account.pdf_export_enabled

  return (
    <div className="mx-auto max-w-3xl">
      <Link to="/dashboard" className="print-hidden inline-flex items-center gap-1.5 text-sm font-medium text-slate-500 hover:text-slate-700">
        <ArrowLeftIcon className="h-4 w-4" />
        Back to dashboard
      </Link>

      <AiDisclaimerBanner className="mt-4" />

      <div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-slate-400">
            {report.mode === 'pdf' ? 'Building plan (PDF)' : 'Text description'} · {formatDate(report.submittedAt)}
          </p>
          <h1 className="mt-1 text-2xl font-semibold text-slate-900">{report.buildingName}</h1>
        </div>
        <div className="flex items-center gap-3">
          {report.complianceScore !== null && (
            <div className="text-right">
              <p className="text-2xl font-semibold text-slate-900">{Math.round(report.complianceScore)}</p>
              <p className="text-xs text-slate-400">/ 100</p>
            </div>
          )}
          <StatusBadge status={report.overallStatus} />
        </div>
      </div>

      <div className="print-hidden mt-4">
        {canExportPdf ? (
          <button
            type="button"
            onClick={() => window.print()}
            className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-1.5 text-sm font-medium text-slate-700 hover:border-slate-300 hover:bg-slate-50"
          >
            <DownloadIcon className="h-4 w-4" />
            Export as PDF
          </button>
        ) : (
          <Link
            to="/pricing"
            className="inline-flex items-center gap-1.5 rounded-lg border border-dashed border-slate-200 px-3 py-1.5 text-sm font-medium text-slate-400"
          >
            <LockIcon className="h-4 w-4" />
            PDF export — upgrade to unlock
          </Link>
        )}
      </div>

      {(report.executiveSummaryMarkdown || report.summary) && (
        <div className="mt-6 rounded-xl border border-slate-200 bg-white p-6">
          <h2 className="text-sm font-semibold text-slate-900">Executive summary</h2>
          <div className="mt-3">
            {report.executiveSummaryMarkdown ? renderMarkdown(report.executiveSummaryMarkdown) : <p className="text-sm text-slate-700">{report.summary}</p>}
          </div>
          {report.generatedBy && <p className="mt-4 text-xs text-slate-400">Generated by {report.generatedBy}</p>}
        </div>
      )}

      <div className="mt-6">
        <h2 className="text-sm font-semibold text-slate-900">Detailed findings</h2>
        {report.detailedChecks.length === 0 ? (
          <p className="mt-2 text-sm text-slate-500">No itemized findings were returned for this report.</p>
        ) : (
          <ul className="mt-3 space-y-3">
            {report.detailedChecks.map((check, index) => (
              <li key={index} className="rounded-xl border border-slate-200 bg-white p-4">
                <div className="flex items-center justify-between gap-3">
                  <p className="font-mono text-xs font-medium text-slate-500">{check.rule_clause}</p>
                  <StatusBadge status={check.status} />
                </div>
                <p className="mt-2 text-sm text-slate-800">{check.finding}</p>
                {check.recommendation && (
                  <p className="mt-2 rounded-lg bg-slate-50 px-3 py-2 text-sm text-slate-600">
                    <span className="font-medium text-slate-700">Recommendation: </span>
                    {check.recommendation}
                  </p>
                )}
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  )
}

export default AnalysisReportPage
